### PR TITLE
Update nunjucks dependency to 3.0.0 or higher

### PR DESCRIPTION
**Pull request by kevinmpowell**
I ran all the tests locally, and they all seem to pass after updating nunjucks to 3.0.0

Let me know if there's anything else that needs to be done to approve this PR.

### CODE REVIEW

**Comment by kevinmpowell** [comment]
@carlosl any chance this can get merged in and added to the npm distribution?

**Comment by revelt** [comment]
nearly 3 months have passed

**Comment by kristijanhusak** [comment]
I'll do it. Thanks for the PR.

**Comment by revelt** [comment]
thank you sir!

**Comment by kristijanhusak** [comment]
I published new version to the npm, 2.1.0., that includes this change.

**Comment by jbrugman** [comment]
But npm install --save-dev gulp-nunjucks-render now gives an error:
`[13:09:16] Requiring external module babel-register
module.js:457
    throw err;
    ^
Error: Cannot find module 'gulp-nunjucks-render'`

Perhaps you need to add a version / tag here as well? Since 2.1.0 cannot be found.

**Comment by revelt** [comment]
Check out [np](https://www.npmjs.com/package/np), it helps with publishing, I use it to do `git push` and `npm publish`. You automatically push to GitHub and publish to npm in one go.
